export const config = {
    RPC_URL: 'http://localhost:26657',
    REST_URL: 'http://localhost:1317',
    // EXPLORER_URL: 'https://www.mintscan.io/juno',
    // STAKING_URL: 'https://juno.omniflix.co/stake',
    NETWORK_NAME: 'Hello',
    NETWORK_TYPE: 'hello',
    CHAIN_ID: 'hello',
    CHAIN_NAME: 'Hello',
    COIN_DENOM: 'STAKE',
    COIN_MINIMAL_DENOM: 'stake',
    COIN_DECIMALS: 0,
    PREFIX: 'cosmos',
    // COIN_TYPE: 118,
    // COINGECKO_ID: 'juno-network',
    DEFAULT_GAS: 0.250000,
    GAS_PRICE_STEP_LOW: 0.001,
    GAS_PRICE_STEP_AVERAGE: 0.0025,
    GAS_PRICE_STEP_HIGH: 0.004,
    // FEATURES: ['stargate', 'ibc-transfer', 'cosmwasm', 'no-legacy-stdTx', 'ibc-go'],
};
